# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: test_database
    ports:
      - 27017:27017
  
  aws-dp-server:
    image: aws-dp-server:1.1
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: test_database
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - mongodb

  