name: Deploy Docker Image to Amazone ECR

# Release 또는 tag(x.x 형식의 tag) 가 push 되는 경우
# Docker Image Build 및 AWS ECR push
on:
  release:
    types: [published]
  push:
    tags:
      - '[0-9].[0-9]'
      
jobs:
  push_to_registry:
    name: Push Docker image to Amazone ECR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # role-to-assume: arn:aws:iam::672550356892:user/ec-user
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: Get Release Tag Name
        id: release_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: aws-dp-server
          IMAGE_TAG: ${{ steps.release_tag.outputs.tag }}
        working-directory: ./server
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG